pins:

  - pin: K1
    # H144_IGN_1
    id: C13
    class: outputs
    type: ign
    ts_name: C2-1 - IGN 1
    function: Coil 1



  - pin: K16
    # H144_LS_3
    id: D11
    class: outputs
    ts_name: C2-16 INJ 3
    function: injector output 3
    type: inj

  - pin: K17
    # H144_IGN_8
    id: E6
    class: outputs
    ts_name: C2-17 - IGN 8
    function: igniter
    type: ign

  - pin: K18
    # H144_IGN_4
    id: E3
    class: outputs
    ts_name: C2-18 - IGN 4
    function: igniter
    type: ign

  - pin: K32
    # H144_LS_2
    id: G8
    class: outputs
    ts_name: C2-32 INJ 2
    function: injector output 2
    type: inj

  - pin: K33
    # H144_IGN_7
    id: B9
    class: outputs
    ts_name: C2-33 - IGN 7
    function: igniter
    type: ign

  - pin: K34
    # H144_IGN_5
    id: E2
    class: outputs
    ts_name: C2-34 - IGN 5
    function: igniter
    type: ign

  - pin: K48
    # H144_LS_8
    id: F14
    class: outputs
    ts_name: C2-48 INJ 8
    function: injector output 8
    type: inj

  - pin: K49
    # H144_LS_5
    id: D9
    class: outputs
    ts_name: C2-49 INJ 5
    function: injector output 5
    type: inj

  - pin: K52
    # H144_LS_6
    id: F12
    class: outputs
    ts_name: C2-52 INJ 6
    function: injector output 6
    type: inj

  - pin: K53
    # H144_IGN_2
    id: E5
    class: outputs
    ts_name: C2-53 - IGN 2
    function: igniter
    type: ign

  - pin: K54
    # H144_IGN_6
    id: B8
    class: outputs
    ts_name: C2-54 - IGN 6
    function: igniter
    type: ign

  - pin: K55
    # H144_IGN_3
    id: E4
    class: outputs
    ts_name: C2-55 - IGN 3
    function: igniter
    type: ign

  - pin: K59
    # H144_IN_SENS4
    id: F6
    class: event_inputs
    ts_name: C2-59 - Cam
    function: Cam Sensor Input
    type: ls
    color: purple

  - pin: K60
    # H144_IN_O2S2
    id: EFI_ADC_1
    class: analog_inputs
    ts_name: C2-60 - Oil Pressure
    function: Oil Pressure
    type: av
    color: purple

  - pin: K63
    # H144_IN_SENS2
    id: F4
    class: event_inputs
    ts_name: C2-63 - Crank
    function: Crank Input
    type: ls
    color: purple

  - pin: K64
    # H144_IN_TPS
    id: EFI_ADC_4
    class: analog_inputs
    ts_name: C2-64 - TPS1
    function: TPS1
    type: av
    color: purple

  - pin: K65
    # H144_IN_MAP1
    id: EFI_ADC_10
    class: analog_inputs
    ts_name: C2-65 - Trans Fluids
    function: Trans Fluids Temperature
    type: av
    color: purple

  - pin: K66
    # H144_IN_AUX1_ANALOG
    id: EFI_ADC_8
    class: analog_inputs
    ts_name: C2-66 - TPS2
    function: TPS2
    type: av
    color: purple

  - pin: K70
    # H144_LS_4
    id: D10
    class: outputs
    ts_name: C2-70 INJ 4
    function: injector output 4
    type: inj

  - pin: K71
    # H144_LS_7
    id: F13
    class: outputs
    ts_name: C2-71 INJ 7
    function: injector output 7
    type: inj

  - pin: K72
    # H144_LS_1
    id: G7
    class: outputs
    ts_name: C2-72 INJ 1
    function: injectpr output 1
    type: inj

  - pin: K73
    function: GND
    type: GND

info:
  cid: GM-E67
  order: 1
  title: Hellen GM E67
  name: Hellen GM E67
  board_url: https://rusefi.com/s/gm-e67
  directory: hellen/hellen-gm-e67
  image:
    file: x2-black.jpg
  pins:
    # auto-generated by PinLine.java
    # 1 16
    # 158 707
    - pin: K1
      x: 158
      y: 168
    - pin: K2
      x: 194
      y: 168
    - pin: K3
      x: 231
      y: 168
    - pin: K4
      x: 267
      y: 168
    - pin: K5
      x: 304
      y: 168
    - pin: K6
      x: 341
      y: 168
    - pin: K7
      x: 377
      y: 168
    - pin: K8
      x: 414
      y: 168
    - pin: K9
      x: 450
      y: 168
    - pin: K10
      x: 487
      y: 168


    - pin: K11
      x: 524
      y: 168
    - pin: K12
      x: 560
      y: 168
    - pin: K13
      x: 597
      y: 168
    - pin: K14
      x: 633
      y: 168
    - pin: K15
      x: 670
      y: 168
    - pin: K16
      x: 707
      y: 168

    # auto-generated by PinLine.java
    # 17 32
    # 158 707
    - pin: K17
      x: 158
      y: 204
    - pin: K18
      x: 194
      y: 204
    - pin: K19
      x: 231
      y: 204
    - pin: K20
      x: 267
      y: 204


    - pin: K21
      x: 304
      y: 204
    - pin: K22
      x: 341
      y: 204
    - pin: K23
      x: 377
      y: 204
    - pin: K24
      x: 414
      y: 204
    - pin: K25
      x: 450
      y: 204
    - pin: K26
      x: 487
      y: 204
    - pin: K27
      x: 524
      y: 204
    - pin: K28
      x: 560
      y: 204
    - pin: K29
      x: 597
      y: 204
    - pin: K30
      x: 633
      y: 204


    - pin: K31
      x: 670
      y: 204
    - pin: K32
      x: 707
      y: 204


    # auto-generated by PinLine.java
    # 33 52
    # 158 856
    - pin: K33
      x: 158
      y: 296
    - pin: K34
      x: 194
      y: 296
    - pin: K35
      x: 231
      y: 296
    - pin: K36
      x: 268
      y: 296
    - pin: K37
      x: 304
      y: 296
    - pin: K38
      x: 341
      y: 296
    - pin: K39
      x: 378
      y: 296
    - pin: K40
      x: 415
      y: 296


    - pin: K41
      x: 451
      y: 296
    - pin: K42
      x: 488
      y: 296
    - pin: K43
      x: 525
      y: 296
    - pin: K44
      x: 562
      y: 296
    - pin: K45
      x: 598
      y: 296
    - pin: K46
      x: 635
      y: 296
    - pin: K47
      x: 672
      y: 296
    - pin: K48
      x: 709
      y: 296
    - pin: K49
      x: 745
      y: 296
    - pin: K50
      x: 782
      y: 296


    - pin: K51
      x: 819
      y: 296
    - pin: K52
      x: 856
      y: 296

    # auto-generated by PinLine.java
    # 53 72
    # 158 856
    - pin: K53
      x: 158
      y: 335
    - pin: K54
      x: 194
      y: 335
    - pin: K55
      x: 231
      y: 335
    - pin: K56
      x: 268
      y: 335
    - pin: K57
      x: 304
      y: 335
    - pin: K58
      x: 341
      y: 335
    - pin: K59
      x: 378
      y: 335
    - pin: K60
      x: 415
      y: 335


    - pin: K61
      x: 451
      y: 335
    - pin: K62
      x: 488
      y: 335
    - pin: K63
      x: 525
      y: 335
    - pin: K64
      x: 562
      y: 335
    - pin: K65
      x: 598
      y: 335
    - pin: K66
      x: 635
      y: 335
    - pin: K67
      x: 672
      y: 335
    - pin: K68
      x: 709
      y: 335
    - pin: K69
      x: 745
      y: 335
    - pin: K70
      x: 782
      y: 335


    - pin: K71
      x: 819
      y: 335
    - pin: K72
      x: 856
      y: 335



    - pin: K73
      x: 800
      y: 200
