pins:
  - pin: U7
    #H144_IN_RES2
    id: F10
    class: switch_inputs
    ts_name: C1-7 Stop/Brake Pedal
    function: Stop/Brake Pedal switch input
    type: din

  - pin: U12
    # H144_OUT_IO11
    id: G2
    class: outputs
    function: MIL Check Engine
    type: hs
    ts_name: C1-12 Check Engine

  - pin: U13
    # H144_OUT_IO5
    id: D2
    class: outputs
    function: Fuel Pump Relay Output
    type: hs
    ts_name: C1-13 - Fuel Pump

  - pin: U14
    function: stm32 BOOT

  - pin: U19
    # H144_IN_VBATT
    id: EFI_ADC_5
    class: analog_inputs
    function: +12V
    ts_name: C1-19 Battery Sense
    type: 12v

  - pin: U25
    # H144_OUT_PWM7
    id: D15
    class: outputs
    function: Tachometer Output
    type: hs
    ts_name: C1-25 Tach

  - pin: U26
    # H144_OUT_IO6
    id: G11
    class: outputs
    ts_name: C1-26 - Starter Relay
    function: Starter Relay
    type: ls
    color: purple

  - pin: U39
    # H144_OUT_PWM6
    id: D14
    class: outputs
    ts_name: C1-39 - VSS Output
    function: VSS Output
    type: hs
    color: purple

  - pin: U40
    # H144_OUT_IO3
    id: G14
    class: outputs
    ts_name: C1-40 - MAIN
    function: Main relay control
    type: ls
    color: purple

  - pin: U44
    # H144_IN_CRANK_ANALOG
    id: EFI_ADC_9
    class: analog_inputs
    function: Primary Fuel Level
    ts_name: C1-44 Primary Fuel Level

  - pin: U45
    # H144_IN_CAM_ANALOG
    id: EFI_ADC_6
    class: analog_inputs
    function: Secondary Fuel Level
    ts_name: C1-45 Secondary Fuel Level

  - pin: U46
    # H144_IN_AUX3_ANALOG
    id: EFI_ADC_15
    class: analog_inputs
    function: Vac Sense
    ts_name: C1-46 Vac Sense

  - pin: U47
    # H144_IN_PPS
    id: EFI_ADC_3
    class: analog_inputs
    ts_name: C1-47 - PPS1
    function: PPS1 analog input
    type: av

  - pin: U49
    # H144_IN_AUX2
    id: EFI_ADC_14
    class: analog_inputs
    ts_name: C1-49 - PPS2
    function: PPS2 analog input
    type: av

  - pin: U56
    # H144_OUT_IO8
    id: G4
    class: outputs
    ts_name: C1-56 - Starter Enable
    function: Starter Enable
    type: ls
    color: purple

info:
  cid: GM-E67
  order: 0
  title: Hellen GM E67
  name: Hellen GM E67
  board_url: https://rusefi.com/s/gm-e67
  directory: hellen/hellen-gm-e67
  image:
    file: blue56.jpg
  pins:
    # auto-generated by PinLine.java from can-log-tools
    # 1 14
    # 201 735
    # 208
    - pin: U1
      x: 201
      y: 208
    - pin: U2
      x: 242
      y: 208
    - pin: U3
      x: 283
      y: 208
    - pin: U4
      x: 324
      y: 208
    - pin: U5
      x: 365
      y: 208
    - pin: U6
      x: 406
      y: 208
    - pin: U7
      x: 447
      y: 208
    - pin: U8
      x: 488
      y: 208
    - pin: U9
      x: 529
      y: 208
    - pin: U10
      x: 570
      y: 208

    - pin: U11
      x: 611
      y: 208
    - pin: U12
      x: 652
      y: 208
    - pin: U13
      x: 693
      y: 208
    - pin: U14
      x: 735
      y: 208


    # auto-generated by PinLine.java from can-log-tools
    # 15 28
    # 201 735
    # 246
    - pin: U15
      x: 201
      y: 246
    - pin: U16
      x: 242
      y: 246
    - pin: U17
      x: 283
      y: 246
    - pin: U18
      x: 324
      y: 246
    - pin: U19
      x: 365
      y: 246
    - pin: U20
      x: 406
      y: 246

    - pin: U21
      x: 447
      y: 246
    - pin: U22
      x: 488
      y: 246
    - pin: U23
      x: 529
      y: 246
    - pin: U24
      x: 570
      y: 246
    - pin: U25
      x: 611
      y: 246
    - pin: U26
      x: 652
      y: 246
    - pin: U27
      x: 693
      y: 246
    - pin: U28
      x: 735
      y: 246


    # auto-generated by PinLine.java from can-log-tools
    # 29 42
    # 201 735
    # 351
    - pin: U29
      x: 201
      y: 351
    - pin: U30
      x: 242
      y: 351

    - pin: U31
      x: 283
      y: 351
    - pin: U32
      x: 324
      y: 351
    - pin: U33
      x: 365
      y: 351
    - pin: U34
      x: 406
      y: 351
    - pin: U35
      x: 447
      y: 351
    - pin: U36
      x: 488
      y: 351
    - pin: U37
      x: 529
      y: 351
    - pin: U38
      x: 570
      y: 351
    - pin: U39
      x: 611
      y: 351
    - pin: U40
      x: 652
      y: 351

    - pin: U41
      x: 693
      y: 351
    - pin: U42
      x: 735
      y: 351

    # auto-generated by PinLine.java from can-log-tools
    # 43 56
    # 201 735
    # 393
    - pin: U43
      x: 201
      y: 393
    - pin: U44
      x: 242
      y: 393
    - pin: U45
      x: 283
      y: 393
    - pin: U46
      x: 324
      y: 393
    - pin: U47
      x: 365
      y: 393
    - pin: U48
      x: 406
      y: 393
    - pin: U49
      x: 447
      y: 393
    - pin: U50
      x: 488
      y: 393

    - pin: U51
      x: 529
      y: 393
    - pin: U52
      x: 570
      y: 393
    - pin: U53
      x: 611
      y: 393
    - pin: U54
      x: 652
      y: 393
    - pin: U55
      x: 693
      y: 393
    - pin: U56
      x: 735
      y: 393
