pins:
  - pin: G7
    # H144_OUT_PWM1
    id: D13
    class: outputs
    function: Alternator Enable
    type: hs
    ts_name: C3-7 - Alternator Enable

  - pin: G16
    # H144_OUT_IO9
    id: G13
    class: outputs
    function: Coolant Pump
    type: hs
    ts_name: C3-16 - Coolant Pump

  - pin: G33
    function: CAN bus low
    type: can

  - pin: G49
    # H144_OUT_IO12
    id: A8
    class: outputs
    function: Radiator Fan Relay
    type: hs
    ts_name: C3-49 - Fan Relay

  - pin: G53
    function: CAN bus high
    type: can

  - pin: G55
    # H144_IN_CLT
    id: EFI_ADC_12
    type: av
    class: analog_inputs
    ts_name: C3-55 - CLT
    function: CLT
    color: purple

  - pin: G56
    # H144_IN_IAT
    id: EFI_ADC_13
    type: av
    class: analog_inputs
    ts_name: C3-56 - IAT
    function: IAT
    color: purple

  - pin: G57
    # H144_IN_AUX4_ANALOG
    id: EFI_ADC_7
    type: av
    class: analog_inputs
    ts_name: C3-57 - A/C Pressure
    function: A/C Pressure
    color: purple

  - pin: G58
    # H144_IN_MAP3
    id: EFI_ADC_2
    type: av
    class: analog_inputs
    ts_name: C3-58 - Baro
    function: Baro Pressure
    color: purple

  - pin: G59
    # H144_IN_MAP2
    id: EFI_ADC_11
    type: av
    class: analog_inputs
    ts_name: C3-59 - MAP
    function: MAP
    color: purple

  - pin: G66
    # H144_IN_VSS
    id: F11
    class: switch_inputs
    function: Vehicle Speed Sensor Input Pos
    type: hall
    ts_name: C3-66 - VSS Input
    color: gray

  - pin: G67
    function: Vehicle Speed Sensor Input Neg
    color: gray

info:
  cid: GM-E67
  title: Hellen GM E67
  name: Hellen GM E67
  board_url: https://rusefi.com/s/gm-e67
  directory: hellen/hellen-gm-e67
  order: 3
  image:
    file: x3-grey.jpg
  pins:
    # auto-generated by PinLine.java
    # 1 16
    # 190 843
    - pin: G1
      x: 190
      y: 203
    - pin: G2
      x: 233
      y: 203
    - pin: G3
      x: 277
      y: 203
    - pin: G4
      x: 320
      y: 203
    - pin: G5
      x: 364
      y: 203
    - pin: G6
      x: 407
      y: 203
    - pin: G7
      x: 451
      y: 203
    - pin: G8
      x: 494
      y: 203
    - pin: G9
      x: 538
      y: 203
    - pin: G10
      x: 581
      y: 203


    - pin: G11
      x: 625
      y: 203
    - pin: G12
      x: 668
      y: 203
    - pin: G13
      x: 712
      y: 203
    - pin: G14
      x: 755
      y: 203
    - pin: G15
      x: 799
      y: 203
    - pin: G16
      x: 843
      y: 203


    # auto-generated by PinLine.java
    # 17 32
    # 190 843
    - pin: G17
      x: 190
      y: 247
    - pin: G18
      x: 233
      y: 247
    - pin: G19
      x: 277
      y: 247
    - pin: G20
      x: 320
      y: 247


    - pin: G21
      x: 364
      y: 247
    - pin: G22
      x: 407
      y: 247
    - pin: G23
      x: 451
      y: 247
    - pin: G24
      x: 494
      y: 247
    - pin: G25
      x: 538
      y: 247
    - pin: G26
      x: 581
      y: 247
    - pin: G27
      x: 625
      y: 247
    - pin: G28
      x: 668
      y: 247
    - pin: G29
      x: 712
      y: 247
    - pin: G30
      x: 755
      y: 247


    - pin: G31
      x: 799
      y: 247
    - pin: G32
      x: 843
      y: 247

    # auto-generated by PinLine.java
    # 33 52
    # 190 1020
    - pin: G33
      x: 190
      y: 357
    - pin: G34
      x: 233
      y: 357
    - pin: G35
      x: 277
      y: 357
    - pin: G36
      x: 321
      y: 357
    - pin: G37
      x: 364
      y: 357
    - pin: G38
      x: 408
      y: 357
    - pin: G39
      x: 452
      y: 357
    - pin: G40
      x: 495
      y: 357


    - pin: G41
      x: 539
      y: 357
    - pin: G42
      x: 583
      y: 357
    - pin: G43
      x: 626
      y: 357
    - pin: G44
      x: 670
      y: 357
    - pin: G45
      x: 714
      y: 357
    - pin: G46
      x: 757
      y: 357
    - pin: G47
      x: 801
      y: 357
    - pin: G48
      x: 845
      y: 357
    - pin: G49
      x: 888
      y: 357
    - pin: G50
      x: 932
      y: 357


    - pin: G51
      x: 976
      y: 357
    - pin: G52
      x: 1020
      y: 357


    # auto-generated by PinLine.java
    # 53 72
    # 190 1020
    - pin: G53
      x: 190
      y: 404
    - pin: G54
      x: 233
      y: 404
    - pin: G55
      x: 277
      y: 404
    - pin: G56
      x: 321
      y: 404
    - pin: G57
      x: 364
      y: 404
    - pin: G58
      x: 408
      y: 404
    - pin: G59
      x: 452
      y: 404
    - pin: G60
      x: 495
      y: 404


    - pin: G61
      x: 539
      y: 404
    - pin: G62
      x: 583
      y: 404
    - pin: G63
      x: 626
      y: 404
    - pin: G64
      x: 670
      y: 404
    - pin: G65
      x: 714
      y: 404
    - pin: G66
      x: 757
      y: 404
    - pin: G67
      x: 801
      y: 404
    - pin: G68
      x: 845
      y: 404
    - pin: G69
      x: 888
      y: 404
    - pin: G70
      x: 932
      y: 404


    - pin: G71
      x: 976
      y: 404
    - pin: G72
      x: 1020
      y: 404
    - pin: G73
      x: 951
      y: 246

