meta: config/boards/hellen_meta.h

pins:
  - pin: 1B
    function:
  - pin: 2B
    function:
  - pin: 3B
    function:
  - pin: 4B
    function:

  - pin: 5B
    function:

  - pin: 6B
    function:
  - pin: 7B
    function:
  - pin: 8B
    function:

  - pin: 9B
    function:


  - pin: 10B
    function:
  - pin: 11B
    function:
  - pin: 12B
    function:


  - pin: 13B
    function:

  - pin: 14B
    function:


  - pin: 15B
    function:

  - pin: 16B
    function:

  - pin: 17B
    function:

  - pin: 18B
    function:

  - pin: 19B
    function:

  - pin: 20B
    function:

  - pin: 21B
    function:

  - pin: 22B
    function:
  - pin: 23B
    function:
  - pin: 24B
    function:

  - pin: 25B
    function:

  - pin: 26B
    function:

  - pin: 27B
    function:

  - pin: 28B
    function:

  - pin: 29B
    function:

  - pin: 30B
    function:

  - pin: 31B
    function:

  - pin: 32B
    function:

  - pin: 33B
    function:

  - pin: 34B
    function:

info:
  cid: 34-4
  order: 1
  title: AlphaX Gold
  directory: hellen/alphax-gold
  name: AlphaX Gold
  image:
    file: 34pins-4k.jpg
  pins:
    - pin: 1B
      x: 75
      y: 90
    - pin: 2B
      x: 95
      y: 90
    - pin: 3B
      x: 120
      y: 90
    - pin: 4B
      x: 145
      y: 90
    - pin: 5B
      x: 165
      y: 90
    - pin: 6B
      x: 190
      y: 90
    - pin: 7B
      x: 215
      y: 90
    - pin: 8B
      x: 240
      y: 90
    - pin: 9B
      x: 265
      y: 90
    - pin: 10B
      x: 85
      y: 120
    - pin: 11B
      x: 105
      y: 120
    - pin: 12B
      x: 130
      y: 120
    - pin: 13B
      x: 155
      y: 120
    - pin: 14B
      x: 180
      y: 120
    - pin: 15B
      x: 205
      y: 120
    - pin: 16B
      x: 225
      y: 120
    - pin: 17B
      x: 245
      y: 120
    - pin: 18B
      x: 85
      y: 150
    - pin: 19B
      x: 110
      y: 150
    - pin: 20B
      x: 130
      y: 150
    - pin: 21B
      x: 155
      y: 150
    - pin: 22B
      x: 180
      y: 150
    - pin: 23B
      x: 205
      y: 150
    - pin: 24B
      x: 225
      y: 150
    - pin: 25B
      x: 245
      y: 150
    - pin: 26B
      x: 74
      y: 180
    - pin: 27B
      x: 98
      y: 180
    - pin: 28B
      x: 122
      y: 180
    - pin: 29B
      x: 146
      y: 180
    - pin: 30B
      x: 170
      y: 180
    - pin: 31B
      x: 195
      y: 180
    - pin: 32B
      x: 220
      y: 180
    - pin: 33B
      x: 245
      y: 180
    - pin: 34B
      x: 265
      y: 180
