meta: config/boards/hellen_mm100_meta.h

pins:
  - pin: 1
    function: Power GND
    type: 2
  - pin: 2
    function: Power GND
  - pin: 3
    function: +12V From Main Relay
  - pin: 4
    meta: MM100_IN_VBATT
    function: Ignition Switch KL15 / Battery Voltage Analog Input
    ts_name: ___ Voltage From Key

  - pin: 5
    meta: MM100_INJ1
    class: outputs
    type: ls
    ts_name: ___ injector output 1
  - pin: 6
    meta: MM100_INJ2
    class: outputs
    type: ls
    ts_name: ___ injector output 2
  - pin: 7
    meta: MM100_INJ3
    class: outputs
    type: ls
    ts_name: ___ injector output 3
  - pin: 8
    meta: MM100_INJ4
    class: outputs
    type: ls
    ts_name: ___ injector output 4
  - pin: 9
    class: outputs
    type: ls
    ts_name: ___ injector output 5
  - pin: 10
    class: outputs
    type: ls
    ts_name: ___ injector output 6
  - pin: 11
    meta: MM100_IGN1
    class: outputs
    ts_name: ___ Coil 1
  - pin: 12
    meta: MM100_IGN2
    class: outputs
    ts_name: ___ Coil 2
  - pin: 13
    meta: MM100_IGN3
    class: outputs
    ts_name: ___ Coil 3
  - pin: 14
    meta: MM100_IGN4
    class: outputs
    ts_name: ___ Coil 4
  - pin: 15
    class: outputs
    ts_name: ___ Coil 5
  - pin: 16
    class: outputs
    ts_name: ___ Coil 6

  - pin: 17
    function: ETB positive DC Motor
    type: etb
    color: purple
  - pin: 18
    function: ETB negative DC Motor
    type: etb
    color: purple

  - pin: 19
    meta: MM100_IGN8
    class: outputs
    type: ls
    ts_name: ___ Main Relay
    function: Main Relay Control
  - pin: 20
    meta: MM100_OUT_PWM5
    class: outputs
    type: ls
    ts_name: ___ Fuel Pump Relay
  - pin: 21
    meta: MM100_OUT_PWM3
    ts_name: ___ Relay Output
    class: outputs
    type: ls

  - pin: 22
    meta: MM100_IGN7
    class: outputs
    type: ls
    ts_name: ___ Relay Output
    color: orange
  - pin: 23
    meta: MM100_OUT_PWM4
    class: outputs
    type: ls
    ts_name: ___ Engine Radiator Fan


  - pin: 24
    ts_name: ___ low side 1.5A output
    class: outputs
    type: ls
  - pin: 25
    ts_name: ___ low side 1.5A output or high side
    class: outputs
    type: ls


  - pin: 103
    function: Analog GND
    type: GND
  - pin: 104
    function: Analog GND
    type: GND
  - pin: 105
    function: Analog GND
    type: GND
  - pin: 106
    function: Analog GND
    type: GND


  - pin: 223
    function: ___ Analog Supply
    color: red
  - pin: 223_2
    function: ___ Analog Supply
    color: red
  - pin: 223_3
    function: ___ Analog Supply
    color: red
  - pin: 223_4
    function: ___ Analog Supply
    color: red

  - pin: 215
    meta: MM100_IN_CLT_ANALOG
    class: analog_inputs
    ts_name: ___ CLT
    function: CLT sensor
  - pin: 227
    class: analog_inputs
    meta: MM100_IN_IAT_ANALOG
    ts_name: ___ IAT
    function: ___ Intake Air Temperature




  - pin: 132
    function: CAN bus high
    type: can

  - pin: 144
    function: CAN bus low
    type: can


info:
  cid: uaefi
  title: uaefi
  directory: hellen/uaefi
  board_url: https://github.com/rusefi/rusefi/wiki/uaefi

